#!/usr/bin/env python3
import csv,html,json,math,shutil
from pathlib import Path
H=lambda x:html.escape(str(x if x is not None else ''))
HERE=Path(__file__).resolve().parent; SRC=HERE.parents[2]/'01-exps/zhangj-8h-202609/2026-09-10-qwen3-8b-three-way-rollout-analysis/data'; OUT=HERE/'data';OUT.mkdir(exist_ok=True)
for name in ('paired_statistics.json','paired_question_outcomes.csv','typical_rollout_cases.json','detailed_rollout_cases.json','validation_semantic_audit.json','typical_cases_external_audit.json','source_manifest.json'):shutil.copy2(SRC/name,OUT/name)
shutil.copy2(SRC/'deepseek_flash_fixed_judge/summary.json',OUT/'deepseek_flash_fixed_judge_summary.json')
stats=json.loads((SRC/'paired_statistics.json').read_text(encoding='utf8'));cases=json.loads((SRC/'detailed_rollout_cases.json').read_text(encoding='utf8'));audit=json.loads((SRC/'validation_semantic_audit.json').read_text(encoding='utf8'));external=json.loads((SRC/'typical_cases_external_audit.json').read_text(encoding='utf8'));deep_summary=json.loads((SRC/'deepseek_flash_fixed_judge/summary.json').read_text(encoding='utf8'))
priority={'254':0,'192':1,'836':2,'863':3};cases.sort(key=lambda c:(priority.get(str(c['instance_id']),99),int(c['instance_id'])))
with (SRC/'paired_question_outcomes.csv').open(encoding='utf8',newline='') as f:questions=list(csv.DictReader(f))
RUNS=(('trace_foldgrpo','FoldGRPO+Trace','#087f8c'),('no_trace','no-Trace','#b05b16'),('trace_only','Trace-only','#a2365a'))
SHORT={'search':'S','open_page':'O','branch':'B','return':'R','finish':'F','context_fold':'折'}
def chart(events):
 ev=[{'k':0,'type':'initial','label':'初始','coverage':0.,'local_hit_ratio':0.,'delta':0.,'block_tokens':0}]+events;n=len(ev);w=max(900,70*n);left=58;right=18;top=28;cov_h=118;zero=205;delta_h=52;plot=w-left-right;xs=[left+(plot*i/max(1,n-1)) for i in range(n)];mx=max([abs(float(e.get('delta') or 0)) for e in ev]or[1])or 1
 lines=[f'<svg class="trajectory" viewBox="0 0 {w} 270" role="img" aria-label="累计词面 coverage 与 Eq.(7) 形式的代数 proxy delta">',f'<rect width="{w}" height="270" fill="#fff"/>','<text x="18" y="18" font-size="14" font-weight="700">累计词面 coverage（折线）与 Eq.(7) 形式的代数 proxy delta（下方柱）</text>']
 for pct in (0,.5,1):
  y=top+cov_h*(1-pct);lines.append(f'<line x1="{left}" y1="{y:.1f}" x2="{w-right}" y2="{y:.1f}" stroke="#dfe4e1"/><text x="{left-8}" y="{y+4:.1f}" text-anchor="end" font-size="10">{pct:.0%}</text>')
 pts=[]
 for x,e in zip(xs,ev):
  cov=float(e.get('coverage')or 0);loc=float(e.get('local_hit_ratio')or 0);y=top+cov_h*(1-cov);pts.append(f'{x:.1f},{y:.1f}');lh=cov_h*loc
  if loc:lines.append(f'<rect x="{x-5:.1f}" y="{top+cov_h-lh:.1f}" width="10" height="{lh:.1f}" fill="#d8b26a" opacity=".38"><title>k={e["k"]} 局部命中={loc:.2f}</title></rect>')
  if e.get('type')=='context_fold':lines.append(f'<line x1="{x:.1f}" y1="{top}" x2="{x:.1f}" y2="{zero+delta_h}" stroke="#70469b" stroke-dasharray="5 4"/>')
 lines.append('<polyline points="'+' '.join(pts)+'" fill="none" stroke="#167c80" stroke-width="3"/>');lines.append(f'<line x1="{left}" y1="{zero}" x2="{w-right}" y2="{zero}" stroke="#69736f"/>')
 for x,e in zip(xs,ev):
  cov=float(e.get('coverage')or 0);y=top+cov_h*(1-cov);d=float(e.get('delta')or 0);bh=delta_h*abs(d)/mx;by=zero-bh if d>=0 else zero;col='#167c80' if d>=0 else '#b34b4b';typ=e.get('type','initial');label=('Q' if typ=='initial' else SHORT.get(typ,typ[:1].upper()))+str(e['k']);tok=e.get('block_tokens',0)
  title=f'k={e["k"]} {e.get("label","初始")}; coverage={cov:.2f}; local={float(e.get("local_hit_ratio")or 0):.2f}; delta={d:.4f}; block tokens={tok}'
  lines.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="4" fill="#167c80" tabindex="0"><title>{H(title)}</title></circle><rect x="{x-4:.1f}" y="{by:.1f}" width="8" height="{max(1,bh):.1f}" fill="{col}"><title>{H(title)}</title></rect><text x="{x:.1f}" y="265" text-anchor="middle" font-size="9">{H(label)}</text>')
 lines.append('</svg>');return ''.join(lines)
def event_rows(events):
 rows=[]
 for e in events:
  hits=', '.join(e['local_gold_hits']) or '无';delta=float(e.get('delta')or 0)
  detail=f'''<details><summary>完整 reasoning / action / observation</summary><p><b>Reasoning</b></p><pre>{H(e.get('reasoning',''))}</pre><p><b>Action</b></p><pre>{H(e['action'])}</pre><p><b>Observation</b></p><pre>{H(e['observation'])}</pre><p><b>完整事件 block</b></p><pre>{H(e['raw_block'])}</pre></details>'''
  rows.append(f'''<tr><td>k={e['k']}</td><td><b>{H(e['label'])}</b><br><small>{H(e['type'])}</small></td><td><div class="step-zh">{H(e['summary_zh'])}</div>{detail}</td><td>{e['action_tokens']} / {e['observation_tokens']} / {e['block_tokens']}</td><td>{e['thinking_tokens']} / {e['tool_call_tokens']} / {e['cumulative_tokens']}</td><td>{H(hits)}</td><td>{e['local_hit_ratio']:.2f} / {e['coverage']:.2f}</td><td>{e['d']:.3f} / {e['V']:.3f} / {delta:+.3f}</td></tr>''')
 return ''.join(rows)
def run_card(key,label,color,r):
 f=r['flow_summary'];notes=''.join('<li>'+H(x)+'</li>'for x in f['notes'])or'<li>未触发额外诊断规则。</li>';seq=H(f['sequence']);facts=[('环境 score',r['score']),('finish accepted','是'if r['finish_accepted']else'否'),('response tokens',r['response_tokens']),('generated tokens',r['generated_tokens']),('事件数',f['event_count']),('事件 tokens',f['event_tokens_total']),('首次 gold k',f['first_gold_k']),('首次满覆盖 k',f['first_full_coverage_k']),('最大 coverage',f"{f['max_coverage']:.0%}"),('重复搜索',r['duplicate_search_calls'])]
 facthtml=''.join(f'<span><b>{H(k)}</b>{H(v if v is not None else "-")}</span>'for k,v in facts)
 return f'''<article class="run" style="--c:{color}"><h3>{H(label)}</h3><div class="facts">{facthtml}</div><section class="flow"><h4>中文流程总结</h4><p>{seq}</p><ul>{notes}</ul></section><div class="chart-scroll">{chart(r['events'])}</div><p class="caption">k 是可恢复事件序号，不是 token 下标。青色折线为当前可见文本的 gold 内容词 coverage；浅金柱为本事件局部命中；下方柱为 coverage 代数 proxy delta。它不是原始 TRACE reward、概率或因果贡献。紫色虚线表示 harness 主上下文折叠。</p><div class="event-scroll"><table class="events"><thead><tr><th>k</th><th>事件</th><th>中文步骤与完整原文</th><th>tokens<br>action / obs / block</th><th>tokens<br>thinking / tool / cumulative</th><th>局部 gold</th><th>local / coverage</th><th>d / V / delta</th></tr></thead><tbody>{event_rows(r['events'])}</tbody></table></div><details class="full"><summary>展开 {H(label)} 完整原始推理 transcript（{len(r['full_transcript']):,} 字符）</summary><pre>{H(r['full_transcript'])}</pre></details></article>'''
def external_html(c):
 rows=[]
 for key,label in (('no-Trace','no-Trace'),('Trace-only','Trace-only')):
  a=external['cases'].get(str(c['instance_id']),{}).get(key)
  if not a: rows.append(f'<tr><td>{H(label)}</td><td>—</td><td>—</td><td>—</td><td>无保存</td></tr>'); continue
  verdict=a.get('deepseek_verdict') or '—'; strict='1' if a.get('historical_strict_trace_em') else '0'; accepted='是' if a.get('deepseek_accepted') else '否'; cand=H(a.get('candidate_answer',''))
  rows.append(f'<tr><td>{H(label)}</td><td>{strict}</td><td>{H(verdict)}</td><td>{accepted}</td><td>{cand}</td></tr>')
 return '<section class="external-audit"><h4>独立一题一条评测（不是上方 validation transcript）</h4><p class="caption">historical strict 是保存的 normalized EM 字段；DeepSeek 是 deepseek-flash、temperature=0、correct 且 confidence≥0.8 才接受。FoldGRPO+Trace 没有同口径独立输出，不能补值。</p><div class="event-scroll"><table class="summary"><thead><tr><th>模型</th><th>strict EM</th><th>DeepSeek verdict</th><th>accepted</th><th>独立候选答案</th></tr></thead><tbody>'+''.join(rows)+'</tbody></table></div></section>'
def case_html(c,i):
 runs=''.join(run_card(k,l,col,c['runs'][k])for k,l,col in RUNS); notices=[];case_type_display=str(c['case_type']).replace('答对','出现 score>0').replace('答错','score=0')
 for key,label,_ in RUNS:
  a=audit['runs'][key].get(str(c['instance_id']),{})
  if a.get('semantic_status')=='grader_false_positive_needs_review': notices.append(f'<li><b>{H(label)}</b>：raw validation score&gt;0，但 finish 中没有 gold 字符串；标记为 <code>grader_false_positive / needs_review</code>。这不是语义正确证据。</li>')
 audit_html=('<div class="warning semantic-audit"><b>语义复核：</b><ul>'+''.join(notices)+'</ul></div>') if notices else '<p class="caption">本案例页面显示的是 raw validation score pattern；score-positive 不自动等于语义答对。</p>'
 return f'''<section id="case-{H(c['instance_id'])}" class="case-detail{' active'if i==0 else''}" data-case="{i}"><h3>q{H(c['instance_id'])} · {H(case_type_display)} · raw score pattern {H(c['pattern'])}</h3><p><b>问题：</b>{H(c['query'])}</p><p><b>Gold：</b><code>{H(c['gold'])}</code></p><div class="warning"><b>阅读边界：</b>score 是 validation environment reward 的原始字段，并按题目聚合取任一正分；它不是固定语义评测。请同时核对完整 transcript、finish 和 gold。</div>{audit_html}{external_html(c)}<div class="runs">{runs}</div></section>'''
PATTERN_MEANINGS={'000':'三组均为 score=0','001':'仅 Trace-only 出现 score>0','010':'仅 no-Trace 出现 score>0','011':'no-Trace 与 Trace-only 出现 score>0','100':'仅 FoldGRPO+Trace 出现 score>0','101':'FoldGRPO+Trace 与 Trace-only 出现 score>0','110':'FoldGRPO+Trace 与 no-Trace 出现 score>0','111':'三组均出现 score>0'}
PATTERN_RUNS=(('1','FoldGRPO+Trace'),('1','no-Trace'),('1','Trace-only'))
def pattern_models(pattern):
 success=[label for bit,(_,label,_) in zip(pattern,RUNS) if bit=='1']
 failed=[label for bit,(_,label,_) in zip(pattern,RUNS) if bit=='0']
 return '、'.join(success) or '无','、'.join(failed) or '无'
patterns=''.join(f'<tr><td><code>{p}</code></td><td>{H(PATTERN_MEANINGS[p])}</td><td>{H(pattern_models(p)[0])}</td><td>{H(pattern_models(p)[1])}</td><td>{n}</td><td>{n / stats["question_count"]:.1%}</td></tr>' for p,n in sorted(stats['patterns'].items()));pairs=''.join(f'<tr><td>{H(x["a_label"])} vs {H(x["b_label"])}</td><td>{x["a_only_correct"]} / {x["b_only_correct"]}</td><td>{x["delta_pp"]:+.2f} pp</td><td>{x["mcnemar_exact_p"]:.3f}</td></tr>'for x in stats['pairwise']);tabs=''.join(f'<button type="button" data-case="{i}" aria-controls="case-{H(c["instance_id"])}">q{H(c["instance_id"])} · {H(c["pattern"])}</button>'for i,c in enumerate(cases));casebody=''.join(case_html(c,i)for i,c in enumerate(cases))
def question_row(q):
 search=' '.join((q['instance_id'],q['difficulty'],q['pattern'],q['query'],q['gold']))
 return f'<tr data-search="{H(search)}" data-difficulty="{H(q["difficulty"])}" data-pattern="{H(q["pattern"])}"><td>{H(q["instance_id"])}</td><td>{H(q["difficulty"])}</td><td>{H(q["pattern"])}</td><td>{H(q["query"])}</td><td>{H(q["gold"])}</td></tr>'
rows=''.join(question_row(q) for q in questions)
css='''*{box-sizing:border-box}body{margin:0;background:#f4f5f2;color:#17202a;font:15px/1.55 Arial,"Microsoft YaHei",sans-serif}a{color:#075d70}header{background:#152228;color:#fff;border-bottom:4px solid #d4973c;padding:14px 4%;display:flex;justify-content:space-between}.hero{background:#fff;padding:24px 4%;border-bottom:1px solid #d7dcd8}main{max-width:1580px;margin:auto;padding:24px 3%}h1{font-size:32px}.scores,.runs{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.score,.run{background:#fff;border:1px solid #d7dcd8;border-top:4px solid var(--c);padding:12px;min-width:0}.score b{display:block;font-size:23px}.warning{border-left:4px solid #8b5c00;background:#fff8e8;padding:12px;margin:12px 0}.tabs{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0}.tabs button{border:1px solid #9ba7a3;background:#fff;padding:8px 11px;cursor:pointer}.tabs button.active{background:#17333a;color:#fff}.case-detail{display:none}.case-detail.active{display:block}.facts{display:grid;grid-template-columns:1fr 1fr;gap:5px}.facts span{border-bottom:1px solid #edf0ee}.facts b{display:block;color:#586573;font-size:12px}.flow{background:#edf4f1;padding:8px 11px;margin:10px 0}.flow h4{margin:0}.chart-scroll,.event-scroll{overflow:auto}.trajectory{display:block;width:100%;min-width:760px;height:auto;border:1px solid #d7dcd8}.caption{font-size:12px;color:#586573}.events,.summary{width:100%;border-collapse:collapse;font-size:12px}.events{min-width:1250px}.events th,.events td,.summary th,.summary td{padding:7px;border:1px solid #d7dcd8;vertical-align:top}.events th,.summary th{background:#edf1ee;position:sticky;top:0}.events pre,.full pre{white-space:pre-wrap;overflow:auto;max-height:440px;background:#10181c;color:#e6f0ec;padding:10px;font:12px/1.45 Consolas,monospace}.events details{max-width:620px}.step-zh{font-weight:600;margin-bottom:5px}.full{margin-top:12px;border:1px solid #aeb8b4;padding:8px}.full summary,.events summary{cursor:pointer;font-weight:700}.allq{max-height:480px;overflow:auto;background:#fff}.filters{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.filters input,.filters select{border:1px solid #9ba7a3;padding:8px;background:#fff;min-width:150px}.allq .summary{min-width:1000px}@media(max-width:900px){main,.hero{padding:14px}.scores,.runs{grid-template-columns:1fr}h1{font-size:25px}.trajectory{min-width:760px}.facts{grid-template-columns:1fr 1fr}}'''
js='''(function(){var buttons=document.querySelectorAll('.tabs button'),cases=document.querySelectorAll('.case-detail');function show(n){var i;for(i=0;i<cases.length;i++){cases[i].className='case-detail'+(i==n?' active':'')}for(i=0;i<buttons.length;i++){buttons[i].className=i==n?'active':'';buttons[i].setAttribute('aria-selected',i==n?'true':'false')}}for(var i=0;i<buttons.length;i++){(function(n){buttons[n].onclick=function(){show(n);location.hash='case-'+this.textContent.split(' ')[0].substring(1)}})(i)}show(0);var input=document.getElementById('question-query'),difficulty=document.getElementById('question-difficulty'),pattern=document.getElementById('question-pattern'),count=document.getElementById('question-count'),rows=document.querySelectorAll('#question-index tbody tr');function filter(){var q=input.value.toLowerCase(),d=difficulty.value,pat=pattern.value,shown=0,i,row;for(i=0;i<rows.length;i++){row=rows[i];var ok=(!q||row.getAttribute('data-search').toLowerCase().indexOf(q)>=0)&&(!d||row.getAttribute('data-difficulty')==d)&&(!pat||row.getAttribute('data-pattern')==pat);row.style.display=ok?'':'none';if(ok){shown++}}count.innerHTML=shown+' / 150'}input.onkeyup=filter;input.oninput=filter;difficulty.onchange=filter;pattern.onchange=filter;filter()})();'''
deep_rows=''.join(f'<tr><td>{H(label)}</td><td>{deep_summary["runs"][key].get("historical_strict_trace_em","—")}/150</td><td>{deep_summary["runs"][key].get("deepseek_accepted","—")}/150</td><td>{deep_summary["runs"][key].get("api_errors","—")}</td></tr>' for key,label in (("no-Trace","no-Trace"),("Trace-only","Trace-only")))
deep_html='<h2>独立评测与 DeepSeek 审核</h2><p class="legend">这是独立一题一条输出，不是上方 step-100 validation rollout；FoldGRPO+Trace 没有保存同口径结果。strict 是历史 normalized EM，DeepSeek 使用 deepseek-flash、temperature=0、correct 且 confidence≥0.8 才接受，API/解析错误 fail-closed。</p><table class="summary"><thead><tr><th>模型</th><th>historical strict normalized EM</th><th>DeepSeek accepted</th><th>API errors</th></tr></thead><tbody>'+deep_rows+'</tbody></table>'
historical_html='<h2>历史 FoldGRPO / TRACE 结果边界</h2><p class="legend">历史资料没有找到与当前 Qwen3-8B、202609 三组完全同口径且明确属于 FoldGRPO+Trace 的独立评测。4B 的真实 FoldGRPO 结果和历史 8B AgentGRPO+TRACE 结果仅作背景，不能填入当前 FoldGRPO+Trace 的缺失值。</p><table class="summary"><thead><tr><th>历史材料</th><th>实际设置</th><th>结果</th><th>当前可比性</th></tr></thead><tbody><tr><td>2026-08-13 Qwen3-4B-Thinking-2507</td><td>FoldGRPO + search_branch</td><td>22/150 = 14.67%</td><td>仅历史 FoldGRPO 背景</td></tr><tr><td>2026-08-24 Qwen3-8B</td><td>AgentGRPO + FoldAgent + frozen-reference TRACE</td><td>step100 strict 16/150；step300 strict 14/150</td><td>不是当前 FoldGRPO+Trace</td></tr><tr><td>当前 Qwen3-8B 202609</td><td>FoldGRPO + Trace</td><td>独立 strict / DeepSeek：—</td><td>没有保存同口径独立输出</td></tr></tbody></table>'
page=f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Qwen3-8B 三组 Rollout 完整轨迹诊断</title><style>{css}</style></head><body><header><b>AgenticRL · Full Trajectory Diagnostics</b><a href="index.html">实验报告主页</a></header><section class="hero"><p>2026-09-10 · Qwen3-8B · BrowseComp · 150 同题配对</p><h1>三组 Rollout 完整轨迹、coverage 与 token 诊断</h1><div class="scores"><div class="score" style="--c:#087f8c"><b>53 / 150</b>FoldGRPO+Trace reward accepted</div><div class="score" style="--c:#b05b16"><b>49 / 150</b>no-Trace reward accepted</div><div class="score" style="--c:#a2365a"><b>62 / 150</b>Trace-only reward accepted</div></div><div class="warning"><b>指标边界：</b>本页 delta 是把词面 coverage 代入 Eq.(7) 形式得到的代数 proxy。当前 validation 没有保存 gold-answer teacher-forced log-likelihood，因此它不是真实 TRACE credit。事件 token 使用本地 Qwen3 tokenizer 离线精确重计。</div></section><main><h2>总体配对统计</h2><div class="event-scroll"><table class="summary"><thead><tr><th>比较</th><th>仅前者 / 仅后者</th><th>差值</th><th>exact McNemar p</th></tr></thead><tbody>{pairs}</tbody></table></div>{deep_html}{historical_html}<h2 id="cases">8 个典型案例：并排事件时间线、coverage 图与完整推理</h2><p>每次选择一个案例，下方并排显示三组模型。图后是逐 k 中文步骤、token 长度和可展开的完整 action/observation；每组末尾保留完整原始 transcript。</p><div class="tabs" role="tablist">{tabs}</div>{casebody}<h2>八种 raw score pattern</h2><p class="legend"><b>位序：</b>FoldGRPO+Trace / no-Trace / Trace-only。每个 code 只描述题目级 validation score&gt;0 的 any-trajectory 聚合，不描述语义正确率；q254 是明确的 grader false positive 反例。</p><table class="summary"><thead><tr><th>raw score code</th><th>中文含义</th><th>score-positive 模型</th><th>score=0 模型</th><th>题数</th><th>150题占比</th></tr></thead><tbody>{patterns}</tbody></table><h2>150 题索引</h2><div class="filters"><input id="question-query" type="search" placeholder="检索 query / gold / ID"><select id="question-difficulty"><option value="">全部 difficulty</option><option value="easy">easy</option><option value="medium">medium</option><option value="hard">hard</option></select><select id="question-pattern"><option value="">全部 pattern</option><option>000</option><option>001</option><option>010</option><option>011</option><option>100</option><option>101</option><option>110</option><option>111</option></select><b id="question-count">150 / 150</b></div><div class="allq"><table id="question-index" class="summary"><thead><tr><th>ID</th><th>难度</th><th>pattern + 中文含义</th><th>query</th><th>gold</th></tr></thead><tbody>{rows}</tbody></table></div><p><a href="data/detailed_rollout_cases.json">下载详细轨迹 JSON</a> · <a href="data/validation_semantic_audit.json">下载 validation 语义审计 JSON</a> · <a href="data/typical_cases_external_audit.json">下载典型案例独立评测 JSON</a> · <a href="data/deepseek_flash_fixed_judge_summary.json">下载 DeepSeek 汇总</a> · <a href="build_diagnostics.py">生成脚本</a></p></main><script>{js}</script></body></html>'''
(HERE/'diagnostics.html').write_text(page,encoding='utf8');print(json.dumps({'questions':len(questions),'cases':len(cases),'runs':len(cases)*3,'html_bytes':len(page.encode())},ensure_ascii=False))
